"""Write docs/CONNECTORS.md from backend/connectors/guides.py (the dashboard uses the same guides)."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.connectors.guides import DESTINATIONS, FORWARDERS, SOURCES, render  # noqa: E402
from backend.connectors.outputs import COMPATIBILITY  # noqa: E402
from backend.services.vendors import SUPPORTED_SOURCES  # noqa: E402

OUT = ROOT / "docs" / "CONNECTORS.md"


def _steps(steps):
    return "\n".join(f"{i}. {render(s)}" for i, s in enumerate(steps, 1))


def _block(text, lang):
    return f"```{lang}\n{render(text)}\n```" if text else ""


def build() -> str:
    parts = [
        "# Connecting TRACELOG",
        "",
        "<!-- Generated by scripts/generate_connector_docs.py from backend/connectors/guides.py. Do not edit. -->",
        "",
        "TRACELOG sits between the devices that produce logs and the tools that analyse them. Devices send "
        "syslog (or a forwarder relays it); TRACELOG archives every line byte-for-byte, parses it, normalises it "
        "to OCSF 1.1.0, hash-chains it, and forwards the OCSF events to any number of destinations at once.",
        "",
        "```",
        "firewalls / IDS / VPN ──syslog UDP·TCP·TLS──┐",
        "rsyslog · syslog-ng relays ─────────────────┤",
        "Fluent Bit · Vector · Cribl ──Splunk HEC────┤──► TRACELOG ──► Splunk · Sentinel · QRadar · Elastic",
        "OpenTelemetry Collector ──OTLP/HTTP─────────┤    archive       Wazuh · OpenSearch · Graylog · Loki",
        "Logstash ──HTTP · Kafka · files─────────────┘    parse         ArcSight/CEF · Datadog · New Relic",
        "                                                  OCSF          OTLP · SOAR webhook · Kafka · Parquet",
        "                                                  hash chain",
        "```",
        "",
        "In the commands below, `TRACELOG_IP` is the TRACELOG server's address. Ports: syslog **514** over UDP "
        "and TCP (`docker compose` publishes 514 and forwards it to 5514 in the container; if you run the server "
        "directly without root it listens on **5514**, so send there instead), syslog over TLS **6514**, and the "
        "API port **8000**, which also serves the Splunk HEC and OTLP receivers. Configure everything in "
        "`config/tracelog.yaml`; every option is shown in `config/tracelog.full-example.yaml`. Secrets are written "
        "as `${ENV_VAR}` and read from the environment, never stored in the file.",
        "",
        "## What TRACELOG understands",
        "",
        "| Parser pack | Vendor | Product | Coverage |",
        "|---|---|---|---|",
    ]
    parts += [f"| `{s['pack']}` | {s['vendor']} | {s['product']} | {s['coverage']} |" for s in SUPPORTED_SOURCES]
    parts += ["", "Lines no pack recognises are still archived, hash-chained and forwarded as OCSF Base Events; "
              "Parser Studio builds a new pack from samples.", "", "## Log sources", ""]
    for s in SOURCES:
        parts += [f"### {s['name']}", "", f"Transport: {s['transport']}. Parser pack: `{s['pack']}`.", "",
                  _steps(s["steps"]), ""]
        if s["snippet"]:
            parts += [_block(s["snippet"], s["lang"]), ""]
    parts += ["## Forwarders and collectors", "",
              "Already running a log pipeline? Point it at TRACELOG without changing the devices.", ""]
    for f in FORWARDERS:
        parts += [f"### {f['name']}", "", _steps(f["steps"]), ""]
        if f["snippet"]:
            parts += [_block(f["snippet"], f["lang"]), ""]
    parts += ["## Destinations", "", "| Output type | Reaches |", "|---|---|"]
    parts += [f"| `{c['output']}` | {c['reaches']} |" for c in COMPATIBILITY]
    parts += ["", "Every output accepts `enabled`, `batch_size`, `flush_seconds`, `max_retries`, "
              "`retry_backoff_seconds`, `timeout_seconds`, `include_raw` and a `filter` "
              "(`classes`, `min_severity_id`, `sources`). Failed batches are retried with backoff and then written "
              "to `data/dead_letter/<output>.ndjson`, so nothing is silently lost; see "
              "[Dead letters](#dead-letters-events-a-destination-did-not-take-and-re-sending-them) for re-sending "
              "them. Add these blocks under `outputs:` in `config/tracelog.yaml`.", ""]
    for d in DESTINATIONS:
        parts += [f"### {d['name']}", "", f"Output type: `{d['type']}`.", "", _steps(d["steps"]), "",
                  _block(d["config"], "yaml"), ""]
    parts += [
        "## Dead letters: events a destination did not take, and re-sending them", "",
        "When an output cannot deliver an event it writes it to `data/dead_letter/<output>.ndjson` instead of "
        "dropping it. Each line records the full OCSF event, the output, the source device, how many delivery "
        "attempts were made, the destination's answer, and a kind:", "",
        "| Kind | Meaning | Re-send |",
        "|---|---|---|",
        "| `undeliverable` | every retry failed: destination down, timeout, HTTP 408/429/5xx | automatic once the "
        "destination answers again, or on request |",
        "| `queue_full` | the output's queue overflowed during a burst | automatic, or on request |",
        "| `rejected` | the destination refused it: HTTP 4xx (bad token, index mapping, payload too large) | only on "
        "request, after fixing the cause |", "",
        "**Automatic re-send.** With `auto_replay: true` (the default) each output retries its `undeliverable` "
        "and `queue_full` dead letters by itself: straight away when a live batch succeeds (the destination is "
        "back), otherwise every `auto_replay_interval_seconds` (30 s), doubling up to "
        "`auto_replay_max_interval_seconds` (15 min) while it stays down. Each pass sends at most "
        "`replay_batches_per_pass` batches, so live traffic keeps flowing while a backlog drains.", "",
        "**Re-send on request.** On the dashboard's Connectors page, an output with waiting dead letters shows "
        "the count by kind, the main reasons, the devices affected and a **Re-send dead letters** button, "
        "with a choice of kinds, the output to send through and a maximum. The same through the API:", "",
        "```bash",
        "# what is waiting, per output (including outputs since removed from the config)",
        "curl -s http://TRACELOG_IP:8000/api/connectors/dead-letters",
        "# the latest entries for one output, with reasons and full events",
        "curl -s 'http://TRACELOG_IP:8000/api/connectors/dead-letters/splunk?limit=20'",
        "# re-send everything waiting for splunk",
        "curl -s -X POST http://TRACELOG_IP:8000/api/connectors/dead-letters/splunk/replay",
        "# only rejected events, after fixing the HEC token; at most 5000",
        "curl -s -X POST 'http://TRACELOG_IP:8000/api/connectors/dead-letters/splunk/replay?kinds=rejected&limit=5000'",
        "# send a removed output's leftovers to the NDJSON archive instead",
        "curl -s -X POST 'http://TRACELOG_IP:8000/api/connectors/dead-letters/old-qradar/replay?to=ocsf-archive'",
        "```", "",
        "The reply gives `state` (`done`, `stopped` when the destination still fails, `limit_reached`, or "
        "`running` if it takes longer than `wait` seconds), `delivered`, `refused_again`, `remaining` and the "
        "error if any.", "",
        "**What a re-send guarantees.** The replay runs in the output's own thread between live batches, so a "
        "destination is never written to from two threads. It claims the waiting file by renaming it (new dead "
        "letters start a fresh file), sends one batch at a time with no retries, and after each accepted batch "
        "saves its position in `<output>.replaying.offset`. If the destination fails, the replay stops and "
        "everything not yet delivered stays exactly where it was for the next attempt. If TRACELOG stops or "
        "crashes mid-replay, the next replay resumes from the saved position, so at most one batch is sent "
        "twice. Elasticsearch, OpenSearch and the Wazuh indexer use the OCSF event uid as the document `_id`, so "
        "even that batch creates no duplicates; for other destinations `metadata.uid` identifies a repeated "
        "event. Entries are removed only after the destination accepted them.", "",
    ]
    parts += [
        "## Reconciliation and the audit report", "",
        "Every outcome of every stored event at every output goes into a hash-chained delivery ledger "
        "(`delivery_batches` and `delivery_events` in the database): delivered live, re-sent from dead letters, "
        "sent again after a restart, filtered out, dead-lettered, or delivered through another output. The "
        "dashboard's **Connectors > Reconcile & audit** tab and `GET /api/audit/reconcile` check, per output:", "",
        "```",
        "owed = delivered + delivered via another output + filtered out + waiting in dead letters + in flight + unaccounted",
        "```", "",
        "where *owed* is every stored event since the output was first configured and **unaccounted must be 0**. "
        "They also verify the per-event integrity chain and the delivery ledger (editing, deleting or reordering "
        "records is detected), and cross-check the dead-letter files against the ledger.", "",
        "**Audit report.** *Generate audit report* on that tab, or `GET /api/audit/report.pdf` and "
        "`GET /api/audit/report.json`, produces a report with the verdict, chain-of-custody checks, the per-output "
        "reconciliation, dead letters waiting, a timeline of outages, re-sends and re-routes, the log sources, and a "
        "fingerprint: the SHA-256 of the JSON report plus the head hashes of both chains. Anyone holding the report "
        "can later check that TRACELOG's ledgers still contain those heads.", "",
        "**After a restart.** Events an output still owed (in its memory queue when TRACELOG stopped, or stored while "
        "outputs were not running) have no outcome in the ledger; TRACELOG finds them at startup and sends them "
        "again from the archive, so a crash cannot silently drop events on their way to a SIEM.", "",
    ]
    parts += ["## Checking the connection", "",
              "- `GET /api/connectors` shows every input and output: counts, last message, errors, queue depth.",
              "- `POST /api/connectors/outputs/<name>/test` sends one OCSF event to that output and reports the "
              "result (the dashboard's Connectors page has a button for this).",
              "- `logger -n TRACELOG_IP -P 514 -d \"test from $(hostname)\"` sends a UDP syslog line from any Linux "
              "host.", ""]
    return "\n".join(parts)


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
