"""Write docs/CONNECTORS.md from backend/connectors/guides.py (the dashboard uses the same guides)."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.connectors.guides import DESTINATIONS, FORWARDERS, SOURCES, render  # noqa: E402
from backend.connectors.outputs import COMPATIBILITY  # noqa: E402
from backend.services.vendors import SUPPORTED_SOURCES  # noqa: E402

OUT = ROOT / "docs" / "CONNECTORS.md"


def _steps(steps):
    return "\n".join(f"{i}. {render(s)}" for i, s in enumerate(steps, 1))


def _block(text, lang):
    return f"```{lang}\n{render(text)}\n```" if text else ""


def build() -> str:
    parts = [
        "# Connecting TRACELOG",
        "",
        "<!-- Generated by scripts/generate_connector_docs.py from backend/connectors/guides.py. Do not edit. -->",
        "",
        "TRACELOG sits between the devices that produce logs and the tools that analyse them. Devices send "
        "syslog (or a forwarder relays it); TRACELOG archives every line byte-for-byte, parses it, normalises it "
        "to OCSF 1.1.0, hash-chains it, and forwards the OCSF events to any number of destinations at once.",
        "",
        "```",
        "firewalls / IDS / VPN ──syslog UDP·TCP·TLS──┐",
        "rsyslog · syslog-ng relays ─────────────────┤",
        "Fluent Bit · Vector · Cribl ──Splunk HEC────┤──► TRACELOG ──► Splunk · Sentinel · QRadar · Elastic",
        "OpenTelemetry Collector ──OTLP/HTTP─────────┤    archive       Wazuh · OpenSearch · Graylog · Loki",
        "Logstash ──HTTP · Kafka · files─────────────┘    parse         ArcSight/CEF · Datadog · New Relic",
        "                                                  OCSF          OTLP · SOAR webhook · Kafka · Parquet",
        "                                                  hash chain",
        "```",
        "",
        "In the commands below, `TRACELOG_IP` is the TRACELOG server's address. Ports: syslog **514** over UDP "
        "and TCP (`docker compose` publishes 514 and forwards it to 5514 in the container; if you run the server "
        "directly without root it listens on **5514**, so send there instead), syslog over TLS **6514**, and the "
        "API port **8000**, which also serves the Splunk HEC and OTLP receivers. Configure everything in "
        "`config/tracelog.yaml`; every option is shown in `config/tracelog.full-example.yaml`. Secrets are written "
        "as `${ENV_VAR}` and read from the environment, never stored in the file.",
        "",
        "## What TRACELOG understands",
        "",
        "| Parser pack | Vendor | Product | Coverage |",
        "|---|---|---|---|",
    ]
    parts += [f"| `{s['pack']}` | {s['vendor']} | {s['product']} | {s['coverage']} |" for s in SUPPORTED_SOURCES]
    parts += ["", "Lines no pack recognises are still archived, hash-chained and forwarded as OCSF Base Events; "
              "Parser Studio builds a new pack from samples.", "", "## Log sources", ""]
    for s in SOURCES:
        parts += [f"### {s['name']}", "", f"Transport: {s['transport']}. Parser pack: `{s['pack']}`.", "",
                  _steps(s["steps"]), ""]
        if s["snippet"]:
            parts += [_block(s["snippet"], s["lang"]), ""]
    parts += ["## Forwarders and collectors", "",
              "Already running a log pipeline? Point it at TRACELOG without changing the devices.", ""]
    for f in FORWARDERS:
        parts += [f"### {f['name']}", "", _steps(f["steps"]), ""]
        if f["snippet"]:
            parts += [_block(f["snippet"], f["lang"]), ""]
    parts += ["## Destinations", "", "| Output type | Reaches |", "|---|---|"]
    parts += [f"| `{c['output']}` | {c['reaches']} |" for c in COMPATIBILITY]
    parts += ["", "Every output accepts `enabled`, `batch_size`, `flush_seconds`, `max_retries`, "
              "`retry_backoff_seconds`, `timeout_seconds`, `include_raw` and a `filter` "
              "(`classes`, `min_severity_id`, `sources`). Failed batches are retried with backoff and then written "
              "to `data/dead_letter/<output>.ndjson`, so nothing is silently lost. Add these blocks under "
              "`outputs:` in `config/tracelog.yaml`.", ""]
    for d in DESTINATIONS:
        parts += [f"### {d['name']}", "", f"Output type: `{d['type']}`.", "", _steps(d["steps"]), "",
                  _block(d["config"], "yaml"), ""]
    parts += ["## Checking the connection", "",
              "- `GET /api/connectors` shows every input and output: counts, last message, errors, queue depth.",
              "- `POST /api/connectors/outputs/<name>/test` sends one OCSF event to that output and reports the "
              "result (the dashboard's Connectors page has a button for this).",
              "- `logger -n TRACELOG_IP -P 514 -d \"test from $(hostname)\"` sends a UDP syslog line from any Linux "
              "host.", ""]
    return "\n".join(parts)


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
